FROM golang:1.23 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/rest
RUN go build -o server server.go
RUN go build -o client client.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/rest/server /server
COPY --from=builder /app/rest/client /client
CMD ["/server"]
