FROM golang:1.23 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/grpc
RUN go build -o server server.go
RUN go build -o client client.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/grpc/server /server
COPY --from=builder /app/grpc/client /client
CMD ["/server"]
